export const GET_FRUITS='GET_FRUITS';
export const FRUIT_ERROR='FRUIT_ERROR';
export const EDIT_FRUIT='EDIT_FRUIT';
export const ADD_NUTRIOTION='ADD_NUTRIOTION';
export const REMOVE_NUTRIOTION='REMOVE_NUTRIOTION';
export const GET_FRUIT_DATA='GET_FRUIT_DATA';
export const ADD_TO_FAVORITE='ADD_TO_FAVORITE';
export const REMOVE_TO_FAVORITE='REMOVE_TO_FAVORITE';
